// ---------------------------------------------------------------------------
// rade-v2 — Clinician EMR renderer
//
// Produces a plain-text clinical note and a structured summary
// from a CaseEnvelope. No dependencies beyond core types.
// ---------------------------------------------------------------------------

import type {
  CaseEnvelope,
  ClinicianSummary,
  RecommendationCategory,
  Urgency,
} from "../core/types";

function urgencyFor(category: RecommendationCategory): Urgency {
  switch (category) {
    case "prophylaxis":
    case "expert_review":
      return "urgent";
    case "observe_or_test":
      return "important";
    case "no_action":
      return "routine";
  }
}

export function renderClinicianNote(envelope: CaseEnvelope): {
  emr_note: string;
  summary: ClinicianSummary;
} {
  const c = envelope.case;
  const a = envelope.assessment!;
  const rec = a.recommendation;
  const risk = a.risk_snapshot;

  const lines: string[] = [];
  const hr = "══════════════════════════════════════════════════════";

  lines.push(hr);
  lines.push("RABIES EXPOSURE RISK ASSESSMENT");
  lines.push(hr);
  lines.push("");

  // Patient
  lines.push("PATIENT CONTEXT:");
  if (c.patient.age_years !== undefined) {
    lines.push(`  Age: ${c.patient.age_years} years`);
  }
  lines.push("");

  // Exposure
  lines.push("EXPOSURE:");
  if (c.exposure.animal_type) lines.push(`  Animal: ${c.exposure.animal_type}`);
  lines.push(`  Location: ${c.exposure.country} / ${c.exposure.subnational_unit}`);
  if (c.exposure.bat_involved) lines.push(`  Bat exposure: ${c.exposure.bat_involved}`);
  if (c.exposure.relevant_exposure !== undefined) {
    lines.push(`  Relevant exposure: ${c.exposure.relevant_exposure ? "yes" : "no"}`);
  }
  lines.push("");

  // Risk
  lines.push("RISK ASSESSMENT:");
  lines.push(`  Risk Tier: ${risk.overall_risk_tier.toUpperCase()}`);
  lines.push(`  Confidence: ${risk.confidence}`);
  lines.push("");

  // Recommendation
  lines.push("RECOMMENDATION:");
  lines.push(`  ${rec.label}`);
  lines.push(`  Category: ${rec.category}`);
  if (rec.requires_escalation) lines.push("  ** REQUIRES ESCALATION **");
  lines.push("");

  // Rationale
  if (a.rationale.lines.length > 0) {
    lines.push("RATIONALE:");
    for (const line of a.rationale.lines) {
      lines.push(`  - ${line}`);
    }
    lines.push("");
  }

  // Key factors
  if (a.key_factors.length > 0) {
    lines.push("KEY FACTORS:");
    for (const f of a.key_factors) {
      lines.push(`  - ${f}`);
    }
    lines.push("");
  }

  // Action items
  if (a.follow_up_tasks.length > 0) {
    lines.push("ACTION ITEMS:");
    for (const t of a.follow_up_tasks) {
      lines.push(`  [${t.priority.toUpperCase()}] ${t.label}`);
    }
    lines.push("");
  }

  // Public health
  if (rec.requires_public_health) {
    lines.push("** PUBLIC HEALTH NOTIFICATION REQUIRED **");
    lines.push("");
  }

  lines.push(hr);
  lines.push(`Generated by RaDE v2 | ${a.timestamp}`);
  lines.push(hr);

  const emr_note = lines.join("\n");

  const summary: ClinicianSummary = {
    recommendation_category: rec.category,
    risk_tier: risk.overall_risk_tier,
    urgency: urgencyFor(rec.category),
    requires_public_health: rec.requires_public_health,
    key_factors: a.key_factors,
    action_items: a.follow_up_tasks.map((t) => t.label),
  };

  return { emr_note, summary };
}
